class TagGenerator

  def self.generate!
    [
      'Indie',
      'Action',
      'Adventure',
      'Casual',
      'Simulation',
      'Strategy',
      'RPG',
      'Early Access',
      'Singleplayer',
      'Free to Play',
      'Violent',
      'Sports',
      'Massively Multiplayer',
      '2D',
      'Atmospheric',
      'Gore',
      'Racing',
      'Multiplayer',
      'Puzzle',
      'Nudity',
      'Sexual Content',
      'Story Rich',
      'Great Soundtrack',
      'Fantasy',
      'Anime',
      'Pixel Graphics',
      'Funny',
      'Difficult',
      'First-Person',
      'VR',
      'Horror',
      'Sci-fi',
      'Shooter',
      'Cute',
      'Arcade',
      'Retro',
      'Colorful',
      'Family Friendly',
      'Co-op',
      'Platformer',
      'Open World',
      'Exploration',
      'Survival',
      'Female Protagonist',
      'FPS',
      'Comedy',
      'Relaxing',
      '3D',
      'Visual Novel',
      'Utilities',
      'Online Co-Op',
      'Third Person',
      'Turn-Based',
      'Sandbox',
      'Replay Value',
      'Action-Adventure',
      'Physics',
      'Realistic',
      'Psychological Horror',
      'Choices Matter',
      'Space',
      'PvP',
      'Point & Click',
      'Mystery',
      'Dark',
      'Local Multiplayer',
      'Tactical',
      'Stylized',
      'Top-Down',
      'Controller',
      'Building',
      'Classic',
      'Management',
      'Education',
      'Movie',
      'Character Customization',
      'Cartoony',
      'Mature',
      'Multiple Endings',
      'Minimalist',
      'Survival Horror',
      'Fast-Paced',
      'Zombies',
      'Local Co-Op',
      'Memes',
      'Old School',
      'Beautiful',
      'Action RPG',
      'Crafting',
      "Shoot 'Em Up",
      'Roguelike',
      'Side Scroller',
      'Short',
      'Puzzle Platformer',
      'Combat',
      'War',
      'Party-Based RPG',
      'Turn-Based Strategy',
      'Procedural Generation',
      'Futuristic',
      'Resource Management',
      'Magic',
      'JRPG',
      'Hack and Slash',
      'Walking Simulator',
      'Historical',
      'PvE',
      'Hand-drawn',
      'Dating Sim',
      'Turn-Based Combat',
      'Medieval',
      '2D Platformer',
      'Dark Fantasy',
      'Cartoon',
      'Romance',
      'Bullet Hell',
      'Stealth',
      'Post-apocalyptic',
      'RPGMaker',
      'RTS',
      'Fighting',
      'Music',
      'Base Building',
      'Competitive',
      'Hidden Object',
      'Experimental',
      'Dungeon Crawler',
      'Drama',
      'Surreal',
      'Third-Person Shooter',
      'Choose Your Own Adventure',
      'Military',
      '4 Player Local',
      'Turn-Based Tactics',
      '3D Platformer',
      'Top-Down Shooter',
      'Interactive Fiction',
      'Isometric',
      'Team-Based',
      'Driving',
      'Moddable',
      'Narration',
      'Dark Humor',
      'Robots',
      'Logic',
      'Cyberpunk',
      'Linear',
      'Card Game',
      'Tower Defense',
      'Economy',
      'Text-Based',
      'Score Attack',
      'Addictive',
      'Aliens',
      'Flight',
      'Perma Death',
      '2.5D',
      'Soundtrack',
      'Abstract',
      'City Builder',
      "1990's",
      "Beat 'em up",
      'Hentai',
      'Thriller',
      'Action Roguelike',
      'World War II',
      'Board Game',
      'Metroidvania',
      'Psychological',
      'Detective',
      'Destruction',
      'Arena Shooter',
      'Emotional',
      'MMORPG',
      'Loot',
      '1980s',
      'Blood',
      'Cinematic',
      'NSFW',
      'Crime',
      'Nature',
      'Strategy RPG',
      'Real Time Tactics',
      'Demons',
      'Dark Comedy',
      'Dystopian',
      'Episodic',
      'Alternate History',
      'Psychedelic',
      'Epic',
      'Wargame',
      'Illuminati',
      'Modern',
      'Investigation',
      'Tactical RPG',
      'Parkour',
      'Immersive Sim',
      'Grand Strategy',
      'Real-Time',
      'Nonlinear',
      'Automobile Sim',
      'Cult Classic',
      'Supernatural',
      'Tabletop',
      'Split Screen',
      'Comic Book',
      'Science',
      'Artificial Intelligence',
      '2D Fighter',
      'Lore-Rich',
      'Rhythm',
      'Co-op Campaign',
      'Life Sim',
      'Space Sim',
      'Open World Survival Craft',
      'CRPG',
      'Match 3',
      'Philosophical',
      'Precision Platformer',
      'Runner',
      'Battle Royale',
      'Steampunk',
      'Political',
      'Swordplay',
      '3D Vision',
      'Mythology',
      'eSports',
      'Dragons',
      'MOBA',
      'Voxel',
      'Satire',
      'Parody',
      'Mechs',
      'Gun Customization',
      'Tanks',
      'Kickstarter',
      'Grid-Based Movement',
      'Remake',
      'Noir',
      'Bullet Time',
      '4X',
      'America',
      'Deckbuilding',
      'Politics',
      'GameMaker',
      'Pirates',
      'Cold War',
      'Hacking',
      'Cats',
      'Ninja',
      'Trading',
      'Trains',
      'Hunting',
      'Card Battler',
      'Mining',
      'Superhero',
      'Hex Grid',
      'Time Travel',
      'Dinosaurs',
      'Gothic',
      'Time Manipulation',
      'Vehicular Combat',
      'God Game',
      'Trading Card Game',
      'Agriculture',
      'Naval',
      'Conspiracy',
      'Colony Sim',
      'Capitalism',
      'Dungeons & Dragons',
      'Fishing',
      'Martial Arts',
      'Western',
      'Assassin',
      'Quick-Time Events',
      'Word Game',
      'Mystery Dungeon',
      'Underwater',
      'Heist',
      'Dynamic Narration',
      'Farming Sim',
      'Underground',
      'Automation',
      'Asynchronous Multiplayer',
      'Crowdfunded',
      'Sequel',
      '3D Fighter',
      'Silent Protagonist',
      'Time Attack',
      'Vampire',
      'Immersive',
      'Soccer',
      'Villain Protagonist',
      'Hero Shooter',
      'Diplomacy',
      'Football',
      'Faith',
      'Political Sim',
      'Naval Combat',
      'Combat Racing',
      'World War I',
      'Sniper',
      'Archery',
      'Sailing',
      'Music-Based Procedural Generation',
      'Party',
      'Narrative',
      'Chess',
      'Looter Shooter',
      'Offroad',
      'Party Game',
      'Solitaire',
      'Gambling',
      'Horses',
      'Mars',
      'On-Rails Shooter',
      'Pinball',
      'Unforgiving',
      'Based On A Novel',
      'Transhumanism',
      'LEGO',
      'Transportation',
      'Foreign',
      'Warhammer 40K',
      'Farming',
      'Trivia',
      'Traditional Roguelike',
      'Werewolves',
      'Boxing',
      'Rome',
      'Nostalgia',
      'Motorbike',
      'Golf',
      'Medical Sim',
      'Intentionally Awkward Controls',
      'Bikes',
      'Asymmetric VR',
      'Creature Collector',
      'Basketball',
      'Jet',
      'Mini Golf',
      'Roguevania',
      'Submarine',
      'Pool',
      'Spelling',
      'Outbreak Sim',
      'Ambient',
      'Wrestling',
      'Spaceships',
      'Baseball',
      'Tennis',
      'Skateboarding',
      'Bowling',
      'Cycling',
      'Hockey',
      'Skating',
      'Motocross',
      'Breathtaking',
      'Rock Music',
      'Well-Written',
      'Skiing',
      'Snowboarding',
      'BMX',
      'ATV',
      'Action RTS',
      '8-bit Music'
    ].each_with_index do |title, i|
      tag = Tag.create!(title: title)

      puts "#{i + 1}. Tag: '#{title}' created"
    end

  end
end
